# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  command = "sed -i s/CONTEXT_PLACEHOLDER/${CONTEXT}/g functions/helpers/inject-context.js && npm run site:build"
  publish = "ship-site"
  functions = "./lambda-built"