module.exports = [
  "Acute internal medicine",
  "Allergy",
  "Anaesthetics",
  "Audio vestibular medicine",
  "Aviation and space medicine",
  "Cardio-thoracic surgery",
  "Cardiology",
  "Chemical pathology",
  "Child and adolescent psychiatry",
  "Clinical genetics",
  "Clinical neurophysiology",
  "Clinical oncology",
  "Clinical pharmacology and therapeutics",
  "Clinical radiology",
  "Community sexual and reproductive health",
  "Dermatology",
  "Diagnostic neuropathology",
  "Emergency medicine",
  "Endocrinology and diabetes mellitus",
  "Forensic histopathology",
  "Forensic psychiatry",
  "Gastroenterology",
  "General (internal) medicine",
  "General practice",
  "General psychiatry",
  "General surgery",
  "Genitourinary medicine",
  "Geriatric medicine",
  "Haematology",
  "Histopathology",
  "Immunology",
  "Infectious diseases",
  "Intensive care medicine",
  "Medical microbiology",
  "Medical oncology",
  "Medical ophthalmology",
  "Medical psychotherapy",
  "Medical virology",
  "Neurology",
  "Neurosurgery",
  "Nuclear medicine",
  "Obstetrics and gynaecology",
  "Occupational medicine",
  "Old age psychiatry",
  "Ophthalmology",
  "Oral and maxillofacial surgery",
  "Otolaryngology",
  "Paediatric and perinatal pathology",
  "Paediatric cardiology",
  "Paediatric surgery",
  "Paediatrics",
  "Palliative medicine",
  "Pharmaceutical medicine",
  "Plastic surgery",
  "Psychiatry of learning disability",
  "Public health medicine",
  "Rehabilitation medicine",
  "Renal medicine",
  "Respiratory medicine",
  "Rheumatology",
  "Sport and exercise medicine",
  "Trauma and orthopaedic surgery",
  "Tropical medicine",
  "Urology",
  "Vascular surgery"
]
